version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: research
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  pipeline:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: research
      DB_USER: user
      DB_PASS: pass
